### Test Home 
GET https://localhost:8080/

### Test Snippet View
GET https://localhost:8080/snippet/view?id=1

### Test Snippet Create
POST https://localhost:8080/snippet/create

### Test Snippet static source
GET https://localhost:8080/static


### Test user login
GET https://localhost:8080/user/signup 